name: 02-WorkFlow-Events
on: 
    push:
    pull_request:
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch:    
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
      - name: Show the Trigger
        run: echo "show the trigger by a(n) ${{github.event_name}} event"


