name: 04-action workfolw
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Action
              uses: actions/checkout@v4
            - name: printing folders 
              run:
                ls 
            - name: setup-node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: installe dependencies
              run:
                npm ci         


