name: 05-1-Event-filter and activites type
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main    
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "running when pr is opend and synchrozed and base branch is main"
