name: PR Event Filter and Activities Type

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Running when PR is opened or synchronized and base branch is main"
